import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { ThemeInit } from "../.flowbite-react/init";

import "./../public/assets/css/globals.css";
import { Providers } from "./providers";
import { LanguageProvider } from '@/contexts/LanguageContext';
import { DirectionProvider, MantineProvider } from '@mantine/core';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "شرکت سرامد",
  description: "Generated by create-flowbite-react",
  icons: {
    icon: "/app/favicon.png",
  },
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="fa" suppressHydrationWarning>
//       <head>
//         <ThemeModeScript />
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeInit />
//         {children}
//       </body>
//     </html>
//   );
// }

//export const metadata = metadata


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <ThemeModeScript />
      </head>
      <LanguageProvider>
        <body className="">
          <Providers>
            <main className="">
              <DirectionProvider initialDirection="rtl">
                <MantineProvider>
                  {children}
                </MantineProvider>
              </DirectionProvider>
            </main>
          </Providers>
        </body>
      </LanguageProvider>
    </html>
  )
}
